
project_id = "ilaftvbwammedhiozylx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions", "storage"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
double_confirm_changes = false
enable_confirmations = false

[analytics]
enabled = false
port = 54324
vector_port = 54325
