// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilaftvbwammedhiozylx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYWZ0dmJ3YW1tZWRoaW96eWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDM0MDcsImV4cCI6MjA2Mjc3OTQwN30.6kp6CspD6zDzfX8gWwlPBJaZ-EZZLlmL_vmKf37kn9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);